// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateJiraClient():Promise<Error>;

export function GetTickets(arg1:number):Promise<Array<main.Ticket>>;

export function GetUserInfo():Promise<string>;

export function Load():Promise<Error>;

export function Save(arg1:string):Promise<Error>;
