// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateJiraClient() {
  return window['go']['main']['User']['CreateJiraClient']();
}

export function GetTickets(arg1) {
  return window['go']['main']['User']['GetTickets'](arg1);
}

export function GetUserInfo() {
  return window['go']['main']['User']['GetUserInfo']();
}

export function Load() {
  return window['go']['main']['User']['Load']();
}

export function Save(arg1) {
  return window['go']['main']['User']['Save'](arg1);
}
