name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install mingw
      uses: egor-tensin/setup-mingw@v1
    
    - name: Install GCC
      uses: egor-tensin/setup-gcc@v1

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
      
    - name: Go mod tidy
      run: go mod tidy
      
    - name: Install wails
      run: go get -u github.com/wailsapp/wails/cmd/wails
      
    - name: Build
      run: wails build -f
